### PR TITLE
fix: fix test process

### PR DESCRIPTION
**Pull request by jiekechoo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Comment by jiekechoo** [comment]
@cherrycl ,please help me how to fix the build error.

**Comment by cherrycl** [comment]
@jiekechoo I created a support ticket [#IT-26505](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-26505) for the issue. Waiting for response.

**Comment by MightyNerdEric** [comment]
recheck

**Comment by jiekechoo** [comment]
> @jiekechoo I created a support ticket [#IT-26505](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-26505) for the issue. Waiting for response.

@cherrycl The ticket has been solved.

**Comment by cherrycl** [comment]
@jiekechoo No, you don't have to add codecov information to readme.

**Pull request merged**
